using System;

namespace GoogleCloudClassLibrary.Places {
    public enum PlacesDetailFields {
        PHOTOS, FORMATTED_ADDRESS, GEOMETRY, NAME, PLACE_ID, ICON, ID, PERMANENTLY_CLOSED, PLUS_CODE, TYPES,
        OPENING_HOURS, RATING, PRICE_LEVEL, ADDRESS_COMPONENT, ADR_ADDRESS, ALT_ID, SCOPE, URL, UTC_OFFSET,
        VICINITY, FORMATTED_PHONE_NUMBER, INTERNATIONAL_PHONE_NUMBER, WEBSITE, REVIEW
    }
}
